### ISSUE TITLE
JAFFE Image Database

### ISSUE THREAD

**Issue by mmmjjjlll** [VarshaMaragi/advanced-machine-learning-project#1]
Hello,

I notice you have included the JAFFE Images with this repository without obtaining permission.

Remove the images immediately or I will report you to Github and take further action.

The correct way to refer to the images is via a link to the information page, which gives further instructions on obtaining them:

http://www.kasrl.org/jaffe.html

Michael Lyons

**Comment by AvinashBukkittu** [comment]
Hi,
  I removed the dataset and added a link to the website. Thanks for letting us know.

**Comment by mmmjjjlll** [comment]
Thank you for the prompt response.
